NumPy provides a wide variety of mathematical functions to operate on arrays efficiently.

In [ ]:
#Basic Arithmetic:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.add(arr, 5))  # Add 5 to each element
print(np.multiply(arr, 2))  # Multiply each element by 2


[6 7 8 9]
[2 4 6 8]


In [ ]:
#Trigonometric Functions:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # Compute sine values
print(np.cos(angles))  # Compute cosine values


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
#Exponents and Logarithms:
numbers = np.array([1, 2, 4, 10])
print(np.exp(numbers))  # Exponential
print(np.log(numbers))  # Natural logarithm


[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.20264658e+04]
[0.         0.69314718 1.38629436 2.30258509]


Create an array of 10 numbers and find the square root of each element.


Compute the tangent of an array containing angles [0, 30, 45, 60, 90] (convert to radians first).

**Random Numbers/Strings/Sequences**

NumPy provides functionality to generate random numbers, strings, and sequences.

In [13]:
import numpy as np
#random integers
print(np.random.randint(1 , 1000 , size=( 4,4 )))  # 5 random integers between 1 and 10


[[254  97 807 885]
 [ 56 954 256 191]
 [351 164 743 308]
 [284 453 796 660]]


In [14]:
#random floats
print(np.random.random(5))  # 5 random floats between 0 and 1


[0.96398606 0.7117822  0.8119303  0.73649846 0.25348161]


In [28]:
#random choice
choices = ['red', 'blue', 'green']
print(np.random.choice(choices, size=10))  # Randomly pick 3 elements


['red' 'red' 'blue' 'blue' 'red' 'blue' 'red' 'blue' 'green' 'blue']


In [27]:
#radom seed
np.random.seed(45)
print(np.random.randint(1, 100, 3))  # Same result with the same seed


[76 31  4]


Generate an array of 10 random integers between 20 and 50.

Create a 3x3 matrix of random floats.

Simulate rolling a die 20 times and find how often each number appears.

In [ ]:
#Simulate rolling a die 20 times and find how often each number appears.
die_rolls = np.random.randint(1, 7, size=20)
unique, counts = np.unique(die_rolls, return_counts=True)
print(dict(zip(unique, counts)))

{1: 3, 2: 2, 3: 6, 4: 5, 5: 2, 6: 2}


Sorting and Searching

NumPy provides efficient tools for sorting arrays and searching for elements.

In [ ]:
#Sorting an Array
arr = np.array([5, 2, 9, 1])
print(np.sort(arr))  # Sort in ascending order


[1 2 5 9]


In [ ]:
#finding indices of sorted arrays
print(arr)
indices = np.argsort(arr)
print(indices)  # Indices of sorted elements


[1 2 3 4 5]
[0 1 2 3 4]


In [ ]:
#searching for elements
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3))  # Find indices where elements are > 3


(array([3, 4]),)


In [ ]:
#binary search
arr = np.array([1, 3, 5, 7])
print(np.searchsorted(arr, 9))  # Find index where 4 can be inserted


4


Sort a 2D array by each row and each column.

Find the indices of all elements greater than 50 in an array of random integers.

Given a sorted array, find the index to insert a given number (use searchsorted).

**Boolean Masking**

Use boolean conditions to filter arrays.

In [ ]:
#Basic Masking
arr = np.array([10, 20, 30, 40])
print(arr[arr > 20])  # Filter elements greater than 20

[30 40]


In [ ]:
#combining conditions
print(arr[(arr > 10) & (arr < 40)])  # Elements between 10 and 40


[20 30]


In [ ]:
#setting values based on conditions
arr[arr > 30] = 99  # Replace values > 30 with 99
print(arr)


[10 20 30 99]


In [ ]:
#Boolean Masking with Matrices,2D arrays
matrix = np.array([[1, 2], [3, 4]])
print(matrix[matrix % 2 == 0])  # Extract even numbers

[2 4]


Find all odd numbers in a 5x5 matrix.

Replace all negative numbers in an array with zero.


Create a mask for values greater than 50 in a random array.

**FILES I/O**

Binary files are efficient for saving and loading large datasets as they preserve data types and structures.

Functions:

np.save(file, array): Saves a single NumPy array in .npy format.

np.savez(file, *args, **kwargs): Saves multiple arrays in a compressed .npz format.

np.load(file): Loads .npy or .npz files back into NumPy arrays.

In [ ]:
import numpy as np

# Saving a single array
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save('array.npy', arr)

# Loading the array
loaded_arr = np.load('array.npy')
print(loaded_arr)

# Saving multiple arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.savez('arrays.npz', array1=arr1, array2=arr2)

# Loading multiple arrays
data = np.load('arrays.npz')
print(data['array1'])
print(data['array2'])


[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


**FILES I/O**

NumPy is generally used for numerical operations on arrays, but it can be used to read and write numerical data from and to files. We'll use numpy.loadtxt() and numpy.savetxt() for this purpose.

If you have a text file, data.txt, with numerical values, you can use numpy.loadtxt() to read it.


In [ ]:
import numpy as np

# Reading a text file with numerical data
data = np.loadtxt('data.txt', delimiter=',')
print(data)


FileNotFoundError: data.txt not found.

In [ ]:
# Replace with the actual file path if it's in a different directory
   file_path = '/path/to/your/data.txt'
   data = np.loadtxt(file_path, delimiter=',')
   print(data)

To write an array to a text file, you can use numpy.savetxt().

In [ ]:
import numpy as np

# Assume you have a NumPy array
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Writing the array to a text file
np.savetxt('output.txt', data, delimiter=',')


**Reading and Writing CSV Files**

If you're dealing with CSV files, numpy.genfromtxt() can be more flexible for reading, and you can still use numpy.savetxt() for writing.

In [ ]:
import numpy as np

# Reading from a CSV file
data = np.genfromtxt('data.csv', delimiter=',')
print(data)


In [ ]:
import numpy as np

# Assume you have a NumPy array
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Writing the array to a text file
np.savetxt('output.csv', data, delimiter=',')

In [ ]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the matrix to a CSV file
file_path = "/mnt/data/matrix.csv"
np.savetxt(file_path, matrix, delimiter=',', fmt='%d')

# Load the matrix back from the CSV file
loaded_matrix = np.loadtxt(file_path, delimiter=',', dtype=int)

matrix, loaded_matrix
