## Numpy array and Basics

In [2]:
import numpy as np

### Creating array from List

In [3]:
arr1d = np.array([1,2,3,4,5])
print(f"1D ARRAY : {arr1d}")

arr2d = np.array([[1,2,3],[4,5,6]])
print(f"2D ARRAY : {arr2d}")

1D ARRAY : [1 2 3 4 5]
2D ARRAY : [[1 2 3]
 [4 5 6]]


Exercise:

Create a 1D array of integers from 1 to 10 and print its properties.

Create a 2D array of shape (3, 3) filled with zeros.

Convert a Python list [1.1, 2.2, 3.3] into a NumPy array and check its data type.


In [4]:
# Q1
array_1d = np.arange(1,11)
print("1d array : ",array_1d)
print("Array Shape",array_1d.shape)
print("Array Dimensions",array_1d.ndim)
print("Array Dtype", arr1d.dtype)

1d array :  [ 1  2  3  4  5  6  7  8  9 10]
Array Shape (10,)
Array Dimensions 1
Array Dtype int64


In [5]:
#Q2
arr = np.zeros([3,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
list = [1.1,2.2,3.3]
arr = np.array([1.1,2.2,3.3])
print(arr)
print(type(arr))

[1.1 2.2 3.3]
<class 'numpy.ndarray'>


Array Manipulation

Reshaping with reshape

Flattening with flatten or ravel

Concatenation and stacking (vstack, hstack, concatenate)


Create a 3D array of shape (2, 3, 4) filled with random integers between 0 and 100.

Reshape a 1D array of size 12 into a 2D array of shape (4, 3).

Concatenate two arrays of size (2, 2) along rows and columns.



In [7]:
#Q1
arr3d = np.random.randint(1,100 , (2,3,4))
print(arr3d)

[[[24 19 93 31]
  [84 48 94 22]
  [42 59 78 58]]

 [[ 7 42 66 73]
  [ 8 44 52 58]
  [84 69 20  1]]]


In [8]:
#q2
arr1d = np.arange(12)
print(arr1d)
reshape = arr1d.reshape((4,3))
print(reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
#q3
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
stacked=np.vstack((arr1,arr2))
print(stacked)

##concatenate
concatenated_rows = np.concatenate((arr1, arr2), axis=0)
concatenated_columns = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along rows:\n", concatenated_rows)
print("Concatenated along columns:\n",concatenated_columns)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


## MEAN, MEDIAN , VARIANCE AND STANDARD DEVIATION

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 5.0
Median: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


Exercise 1: Properties of ndarray

Create a NumPy array from the list [1, 2, 3, 4, 5, 6].

Print the shape, size, data type (dtype), and number of dimensions (ndim) of the array.

Reshape the array into a 2x3 matrix and verify the properties again.

In [13]:
array1 = np.array([1,2,3,4,5,6])
print("shape",array1.shape)
print("dtype",array1.dtype)
print("dimensions",array1.ndim)
print("reshape",array1.reshape((2,3)))


shape (6,)
dtype int64
dimensions 1
reshape [[1 2 3]
 [4 5 6]]


Exercise 2: Array Creation

Create the following arrays using NumPy functions:

A 3x3 array filled with zeros.

A 4x4 identity matrix using np.eye.

An array of evenly spaced numbers from 0 to 10 with 5 elements using np.
linspace.

An array of numbers from 10 to 50 with a step of 5 using np.arange.

Print each array along with its properties.

In [21]:
array01=np.zeros((3,3))
print("zeroes", array01)
identity = np.eye(4,4)
print(identity)

linspace_array = np.linspace(0, 10, 5)
print("\n linespace array \n",linspace_array)

arr11=np.arange(10,51,5)
print("arange",arr11)

zeroes [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 linespace array 
 [ 0.   2.5  5.   7.5 10. ]
arange [10 15 20 25 30 35 40 45 50]


Exercise 3: Array Manipulation

Create a 1D array with 12 elements using np.arange(1, 13).

Reshape it into a 3x4 matrix.

Flatten the reshaped matrix using flatten and ravel. Observe the differences.

Create a second array, [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]].

Concatenate the two arrays vertically and horizontally using vstack and hstack.

In [36]:
arr1d = np.arange(1,13).reshape(3,4)
print(arr1d)
# print("flattened",arr1d.flatten())
# print("ravel",arr1d.ravel())

arr2d = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
print("2d array" , arr2d)

stacked=np.vstack((arr1d,arr2d))
print("vstacked\n",stacked)
hstacked=np.hstack((arr1d,arr2d))
print("horizontal stacked \n",hstacked)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2d array [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
vstacked
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
horizontal stacked 
 [[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
