## Numpy array and Basics

In [48]:
import numpy as np

### Creating array from List

In [43]:
arr1d = np.array([1,2,3,4,5])
print(f"1D ARRAY : {arr1d}")

arr2d = np.array([[1,2,3],[4,5,6]])
print(f"2D ARRAY : {arr2d}")

1D ARRAY : [1 2 3 4 5]
2D ARRAY : [[1 2 3]
 [4 5 6]]


Exercise:

Create a 1D array of integers from 1 to 10 and print its properties.

Create a 2D array of shape (3, 3) filled with zeros.

Convert a Python list [1.1, 2.2, 3.3] into a NumPy array and check its data type.


In [44]:
# Q1
array_1d = np.arange(1,11)
print("1d array : ",array_1d)
print("Array Shape",array_1d.shape)
print("Array Dimensions",array_1d.ndim)
print("Array Dtype", arr1d.dtype)

1d array :  [ 1  2  3  4  5  6  7  8  9 10]
Array Shape (10,)
Array Dimensions 1
Array Dtype int64


In [45]:
#Q2
arr = np.zeros([3,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [46]:
list = [1.1,2.2,3.3]
arr = np.array([1.1,2.2,3.3])
print(arr)
print(type(arr))

[1.1 2.2 3.3]
<class 'numpy.ndarray'>


Array Manipulation

Reshaping with reshape

Flattening with flatten or ravel

Concatenation and stacking (vstack, hstack, concatenate)


Create a 3D array of shape (2, 3, 4) filled with random integers between 0 and 100.

Reshape a 1D array of size 12 into a 2D array of shape (4, 3).

Concatenate two arrays of size (2, 2) along rows and columns.



In [50]:
#Q1
arr3d = np.random.randint(1,100 , (2,3,4))
print(arr3d)

[[[25 55 46  3]
  [16 36 92 79]
  [21  9 19 23]]

 [[66 40 63 25]
  [20 79  8 85]
  [38 33 37 29]]]


In [63]:
#q2
arr1d = np.arange(12)
print(arr1d)
reshape = arr1d.reshape((4,3))
print(reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [71]:
#q3
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
stacked=np.vstack((arr1,arr2))
print(stacked)

##concatenate
concatenated_rows = np.concatenate((arr1, arr2), axis=0)
concatenated_columns = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along rows:\n", concatenated_rows)
print("Concatenated along columns:\n",concatenated_columns)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


## MEAN, MEDIAN , VARIANCE AND STANDARD DEVIATION

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 5.0
Median: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
