By the end of this lecture, students will:

- Understand the purpose and importance of NumPy in data science and numerical computing.

- Learn how to create, manipulate, and perform operations on arrays.

- Explore key NumPy functionalities, including array indexing, broadcasting, and linear algebra.

- Solve real-world problems using NumPy.

What is NumPy?

- Numerical Python: A library for numerical computations.

- Efficient handling of large datasets.

- Core object: ndarray (N-dimensional array).

In [43]:
pip install numpy

In [44]:
import numpy as np

Basics of ndarray

- Properties of ndarray: shape, size, dtype, ndim

In [42]:
import numpy as np

arr = np.array( [[1, 2, 3],[4, 5.5, 6]
                ,[7, 8, 9]
                ,[10,11,12]]
                )
print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("Size:\n", arr.size)
print("Data Type:\n", arr.dtype)

Array:
 [[ 1.   2.   3. ]
 [ 4.   5.5  6. ]
 [ 7.   8.   9. ]
 [10.  11.  12. ]]
Shape:
 (4, 3)
Size:
 12
Data Type:
 float64


Exercise:

Create a 1D array of integers from 1 to 10 and print its properties.

Create a 2D array of shape (3, 3) filled with zeros.

Convert a Python list [1.1, 2.2, 3.3] into a NumPy array and check its data type.

In [17]:
arr1 = np.arange(1, 65)
print("Array:", arr1)
arr=arr1.reshape(4,4,4)
print(arr)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)
print(arr1.ndim)
print(arr.ndim)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
Shape: (64,)
Size: 64
Data Type: int64
1
3


In [21]:
arr2 = np.zeros((4, 4))
print("Array:\n", arr2)
print("\nShape:", arr2.shape)
print("\nSize:", arr2.size)
print("\nData Type:", arr2.dtype)
print("Dimension of array:",arr2.ndim)

Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Shape: (4, 4)

Size: 16

Data Type: float64
Dimension of array: 2


In [22]:
arr3= np.array([1.1, 2.2, 3.3])
print("Array:", arr3)
print("Shape:", arr3.shape)
print("Size:", arr3.size)
print("Data Type:", arr3.dtype)
print("Dimension of array:",arr3.ndim)

Array: [1.1 2.2 3.3]
Shape: (3,)
Size: 3
Data Type: float64
Dimension of array: 1


In [23]:
lst_1=[1,2,3,4,5,6,7,8,9,10]
print("List is:",lst_1,"and type of list is:\n")
print(type(lst_1))
arr4 = np.array(lst_1)
print("\nArray is:\n",arr4)
print("\nType of array is:",type(arr4))

List is: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] and type of list is:

<class 'list'>

Array is:
 [ 1  2  3  4  5  6  7  8  9 10]

Type of array is: <class 'numpy.ndarray'>


Array Creation

From lists or tuples

Using np.zeros, np.ones, np.arange, np.linspace, and np.eye

In [24]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 4))
arange_array = np.arange(0, 31, 3)
linspace_array = np.linspace(0, 15, 5)
eye_array = np.eye(3)
print(zeros_array,"\n\n")

print( ones_array,"\n\n")

print(arange_array,"\n\n")

print(linspace_array,"\n\n")

print(eye_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


[ 0  3  6  9 12 15 18 21 24 27 30] 


[ 0.    3.75  7.5  11.25 15.  ] 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Array Manipulation

Reshaping with reshape

Flattening with flatten or ravel

Concatenation and stacking (vstack, hstack, concatenate)

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7,8,9],[10,11,12]])
reshaped = arr.reshape(3, 2)
flattened = arr.flatten()
stacked = np.vstack((arr,arr2))
print("\nReshaped:", reshaped)
print("\nFlattened:", flattened)
print("\nStacked:\n", stacked)


Reshaped: [[1 2]
 [3 4]
 [5 6]]

Flattened: [1 2 3 4 5 6]

Stacked:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Create a 3D array of shape (2, 3, 4) filled with random integers between 0 and 100.

Reshape a 1D array of size 12 into a 2D array of shape (4, 3).

Concatenate two arrays of size (2, 2) along rows and columns.

In [ ]:
arr4=np.arange(1,13)
print("1D Array is: ", arr4)
arr5=arr4.reshape(4,3)
print("Array has been reshaped into 4 by 3 i.e \n",arr5)

1D Array is:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Array has been reshaped into 4 by 3 i.e 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr3d= np.random.randint(0, 100, (2, 3, 4))
print("Random integer arr:\n",arr3d)

Random integer arr:
 [[[27 48 52 66]
  [75 19 98  2]
  [ 5 75 42 56]]

 [[ 4 42 42 65]
  [62 29 10 91]
  [54 38 56 44]]]


In [ ]:
arr1d = np.arange(12)
print("1D array:\n",arr1d)
reshaped = arr1d.reshape(4, 3)
print("Reshaped array:\n",reshaped)

1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
#Concatenate two arrays of size (2, 2) along rows and columns.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_rows = np.concatenate((arr1, arr2), axis=0)
concatenated_columns = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along rows:\n", concatenated_rows)
print("Concatenated along columns:\n",concatenated_columns)

Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


Arithmetic Operations

Element-wise operations: +, -, **, /, exponential

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b,"\n")
print(a * b,"\n")
print(a ** 2,"\n")

[5 7 9] 

[ 4 10 18] 

[1 4 9] 



Statistical Functions

Mean, median, variance, standard deviation

1. Mean:

The mean (also called the average) is calculated by summing up all the values in a dataset and then dividing by the total number of values.

Formula:


Mean (μ) = (Sum of all values) / (Total number of values)
Use code with caution
Example:

For the dataset [2, 4, 6, 8, 10]:

Mean = (2 + 4 + 6 + 8 + 10) / 5 = 6

2. Median:

The median is the middle value in a dataset when it is ordered from least to greatest. If there is an even number of values, the median is the average of the two middle values.

Steps:

Sort the dataset in ascending order.
If the dataset has an odd number of values, the median is the middle value.
If the dataset has an even number of values, the median is the average of the two middle values.
Example:

For the dataset [2, 4, 6, 8, 10]: Median = 6
For the dataset [2, 4, 6, 8]: Median = (4 + 6) / 2 = 5
3. Variance:

Variance measures how spread out the data is from the mean. It's calculated by finding the average of the squared differences between each data point and the mean.

Formula:


Variance (σ²) = Σ (xi - μ)² / (N -1)  for sample Variance
Variance (σ²) = Σ (xi - μ)² / N for population Variance
Use code with caution
where:

xi = each data point
μ = the mean
N = the total number of data points
Example:

For the dataset [2, 4, 6, 8, 10] (where the mean is 6):

Variance = [(2-6)² + (4-6)² + (6-6)² + (8-6)² + (10-6)²] / 4 = 8

4. Standard Deviation:

The standard deviation is the square root of the variance. It provides a more interpretable measure of data spread in the original units of the data.

Formula:


Standard Deviation (σ) = √Variance
Use code with caution
Example:

For the dataset [2, 4, 6, 8, 10] (where the variance is 8):

Standard Deviation = √Variance = √8 ≈ 2.83


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 5.0
Median: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


Exercise 1: Properties of ndarray

Create a NumPy array from the list [1, 2, 3, 4, 5, 6].

Print the shape, size, data type (dtype), and number of dimensions (ndim) of the array.

Reshape the array into a 2x3 matrix and verify the properties again.


Exercise 2: Array Creation

Create the following arrays using NumPy functions:

A 3x3 array filled with zeros.

A 4x4 identity matrix using np.eye.

An array of evenly spaced numbers from 0 to 10 with 5 elements using np.
linspace.

An array of numbers from 10 to 50 with a step of 5 using np.arange.

Print each array along with its properties.

Exercise 3: Array Manipulation

Create a 1D array with 12 elements using np.arange(1, 13).

Reshape it into a 3x4 matrix.

Flatten the reshaped matrix using flatten and ravel. Observe the differences.

Create a second array, [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]].

Concatenate the two arrays vertically and horizontally using vstack and hstack.

Exercise 4: Arithmetic Operations

Create two arrays:

A = np.array([1, 2, 3, 4])

B = np.array([5, 6, 7, 8])

Perform the following element-wise operations:

Addition: A + B

Subtraction: A - B

Multiplication: A * B

Division: A / B

Exponentiation: A ** 2

Calculate the exponential of all elements in A.


In [ ]:
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)
B=np.arange(13,25).reshape(3,4)
print(B)
print("Addition:\n", A + B)# Adding two arrays
print("Subtraction:\n", B - A)
print("Multiplication:\n", A * B)
print("Division:\n", A / B)
print("Exponentiation:\n", A ** 2)
print("Exponential of A:\n", np.exp(A))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Addition:
 [[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
Subtraction:
 [[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
Multiplication:
 [[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]
Division:
 [[0.07692308 0.14285714 0.2        0.25      ]
 [0.29411765 0.33333333 0.36842105 0.4       ]
 [0.42857143 0.45454545 0.47826087 0.5       ]]
Exponentiation:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Exponential of A:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]


Exercise 5: Statistical Functions

Create an array: data = np.array([2, 4, 6, 8, 10, 12]).

Calculate and print the following statistical measures:

Mean

Median

Variance

Standard Deviation

Create a 2x3 matrix with random integers between 1 and 10. Calculate the mean along rows and columns.

In [ ]:
#Exercise 1
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5, 6])

# Properties
print("Array:", array)
print("Shape:", array.shape)
print("Size:", array.size)
print("Data Type (dtype):", array.dtype)
print("Number of Dimensions (ndim):", array.ndim)

# Reshape the array
reshaped_array = array.reshape(2, 3)
print("\nReshaped Array:\n", reshaped_array)
print("Shape after reshape:", reshaped_array.shape)


Array: [1 2 3 4 5 6]
Shape: (6,)
Size: 6
Data Type (dtype): int64
Number of Dimensions (ndim): 1

Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Shape after reshape: (2, 3)


In [ ]:
#Array Creation
# Create arrays
zeros_array = np.zeros((3, 3))
identity_matrix = np.eye(4)
linspace_array = np.linspace(0, 10, 5)
arange_array = np.arange(10, 51, 5)

# Print arrays
print("3x3 Zeros Array:\n", zeros_array)
print("\n4x4 Identity Matrix:\n", identity_matrix)
print("\nLinspace Array (0 to 10, 5 elements):\n", linspace_array)
print("\nArange Array (10 to 50, step 5):\n", arange_array)


3x3 Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Linspace Array (0 to 10, 5 elements):
 [ 0.   2.5  5.   7.5 10. ]

Arange Array (10 to 50, step 5):
 [10 15 20 25 30 35 40 45 50]


In [31]:
#Array Manipulation
# Create a 1D array
array = np.arange(1, 13)

# Reshape to 3x4 matrix
reshaped_array = array.reshape(3, 4)
print("Reshaped Array:\n", reshaped_array)

# Flatten with flatten and ravel
flattened = reshaped_array.flatten()
raveled = reshaped_array.ravel()
print("\nFlattened Array:", flattened)
print("Raveled Array:", raveled)

# Create a second array
second_array = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])

# Concatenate arrays
vstacked = np.vstack((reshaped_array, second_array))
hstacked = np.hstack((reshaped_array, second_array))
print("\nVertically Stacked Arrays:\n", vstacked)
print("\nHorizontally Stacked Arrays:\n", hstacked)


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Vertically Stacked Arrays:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Horizontally Stacked Arrays:
 [[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
#Array Arithematic Opearations
# Create two arrays
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

# Element-wise operations
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)
print("Exponentiation:", A ** 2)

# Exponential of A
exp_A = np.exp(A)
print("\nExponential of A:", exp_A)


Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Exponentiation: [ 1  4  9 16]

Exponential of A: [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#Statistical Functions
# Create an array
data = np.array([2, 4, 6, 8, 10, 12])

# Statistical measures
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

# Create a random 2x3 matrix
random_matrix = np.random.randint(1, 10, (2, 3))
print("\nRandom 2x3 Matrix:\n", random_matrix)

# Mean along rows and columns
print("Mean along rows:\n", np.mean(random_matrix, axis=1))
print("Mean along columns:\n", np.mean(random_matrix, axis=0))


Mean: 7.0
Median: 7.0
Variance: 11.666666666666666
Standard Deviation: 3.415650255319866

Random 2x3 Matrix:
 [[9 4 5]
 [6 3 5]]
Mean along rows:
 [6.         4.66666667]
Mean along columns:
 [7.5 3.5 5. ]


Matrix Operations

Dot product: np.dot

Matrix multiplication: @

Transpose: T

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("\n",a)
print("\n",b)
print("Dot Product:\n", np.dot(a, b))
print("Transpose:", a.T)


 [[1 2]
 [3 4]]

 [[5 6]
 [7 8]]
Dot Product:
 [[19 22]
 [43 50]]
Transpose: [[1 3]
 [2 4]]


Transpose of a Matrix

The transpose of a matrix is obtained by interchanging its rows and columns. More formally, if A is an m x n matrix (with m rows and n columns), its transpose, denoted by A<sup>T</sup> (or A' ), is an n x m matrix where the element in the i-th row and j-th column of A<sup>T</sup> is the element in the j-th row and i-th column of A.

Mathematical Notation:


[A<sup>T</sup>]<sub>ij</sub> = [A]<sub>ji</sub>
Use code with caution
where:

[A<sup>T</sup>]<sub>ij</sub> represents the element in the i-th row and j-th column of the transposed matrix A<sup>T</sup>.
[A]<sub>ji</sub> represents the element in the j-th row and i-th column of the original matrix A.
Example:

Let's say we have a matrix A:


A = | 1  2  3 |
    | 4  5  6 |
Use code with caution
To find the transpose A<sup>T</sup>, we interchange the rows and columns:


A<sup>T</sup> = | 1  4 |
          | 2  5 |
          | 3  6 |
Use code with caution
In simpler terms:

Identify the elements: Look at each element in the original matrix and its position (row and column).
Swap positions: For the transposed matrix, place that element in the reversed position (column becomes row, row becomes column).
Repeat: Do this for all elements of the original matrix.
Key Properties of Transpose:

(A<sup>T</sup>)<sup>T</sup> = A: The transpose of the transpose of a matrix is the original matrix.
(A + B)<sup>T</sup> = A<sup>T</sup> + B<sup>T</sup>: The transpose of a sum of matrices is the sum of their transposes.
(kA)<sup>T</sup> = kA<sup>T</sup>: The transpose of a scalar multiple of a matrix is the scalar multiple of the transpose.
(AB)<sup>T</sup> = B<sup>T</sup>A<sup>T</sup>: The transpose of a product of matrices is the product of their transposes in reverse order.

Perform element-wise addition and multiplication on two 3x3 matrices.

Compute the dot product of two vectors.

Compute the cross product of two vectors.

Calculate the mean and variance of a random 2D array.

In [ ]:
#Perform element-wise addition and multiplication on two 3x3 matrices.

import numpy as np

# Create two 3x3 matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition_result = matrix1 + matrix2
print("Element-wise Addition:\n", addition_result)

# Element-wise multiplication
multiplication_result = matrix1 * matrix2
print("\nElement-wise Multiplication:\n", multiplication_result)

Element-wise Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


The dot product, also known as the scalar product, is an operation performed on two vectors of the same dimension (they have the same number of elements). The result of the dot product is a single scalar value (a number).

Here's how it's calculated:

Element-wise Multiplication: You multiply the corresponding elements of the two vectors.

Summation: You add up all the products obtained in the previous step.

Formula:

If you have two vectors, a = [a1, a2, a3, ..., an] and b = [b1, b2, b3, ..., bn], their dot product is calculated as follows:

a · b = (a1 * b1) + (a2 * b2) + (a3 * b3) + ... + (an * bn)

Example:

Let's say we have the vectors:

a = [1, 2, 3] b = [4, 5, 6]

The dot product would be:

a · b = (1 * 4) + (2 * 5) + (3 * 6) = 4 + 10 + 18 = 32

Geometric Interpretation:

The dot product also has a geometric interpretation. It can be expressed in terms of the magnitudes of the vectors and the cosine of the angle between them:

a · b = ||a|| ||b|| cos(θ)

where:

||a|| and ||b|| are the magnitudes (lengths) of vectors a and b, respectively.
θ is the angle between the two vectors.
This geometric interpretation is useful in various applications, such as determining if two vectors are orthogonal (perpendicular, meaning their dot product is 0) or finding the projection of one vector onto another.

In [32]:
# Compute the dot product of two vectors.

import numpy as np

# Create two vectors
vector1 = np.array([3, 4, 5])
vector2 = np.array([3, 4, 5])

# Compute the dot product
dot_product = np.dot(vector1, vector2)

# Print the result
print("Dot product:", dot_product)

Dot product: 50


dot_product = np.dot(vector1, vector2): This is the core of the calculation. np.dot() is a NumPy function that calculates the dot product of two arrays (in this case, our vectors). The dot product is a mathematical operation that results in a single number.


The Cross Product in Mathematics
The cross product, also known as the vector product, is a binary operation on two vectors in three-dimensional space. It results in a third vector that is perpendicular to both of the original vectors and has a magnitude equal to the area of the parallelogram spanned by those vectors.

Here's a breakdown:

Input: Two vectors, usually denoted as a and b, in three-dimensional space (R³).

Output: A third vector, denoted as a × b, also in three-dimensional space.

Properties:

Perpendicularity: The resulting vector (a × b) is perpendicular to both a and b. This means the dot product of (a × b) with either a or b is zero.
Magnitude: The magnitude (length) of the cross product vector is given by: ||a × b|| = ||a|| ||b|| sin(θ) where:
||a|| and ||b|| are the magnitudes of vectors a and b, respectively.
θ is the angle between vectors a and b (0° ≤ θ ≤ 180°).
Direction: The direction of the cross product vector is determined by the right-hand rule. If you point your right-hand fingers in the direction of vector a and curl them towards vector b, your thumb will point in the direction of a × b.
Geometric Interpretation:

The magnitude of the cross product represents the area of the parallelogram formed by vectors a and b.
The direction of the cross product indicates the orientation of the plane containing a and b.
Formula: If a = (a₁, a₂, a₃) and b = (b₁, b₂, b₃), then the cross product is calculated as follows:

a × b = (a₂b₃ - a₃b₂, a₃b₁ - a₁b₃, a₁b₂ - a₂b₁)

Important Considerations:

The cross product is not commutative, meaning a × b ≠ b × a. In fact, a × b = -(b × a).
The cross product is only defined for vectors in three-dimensional space.

In [ ]:
# Compute the cross product of two vectors

import numpy as np

# Example vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Compute the cross product
cross_product = np.cross(vector_a, vector_b)

# Print the result
print("Cross product:", cross_product)

Cross product: [-3  6 -3]


Broadcasting

Adding scalar to an array

Operations between arrays of different shapes

In [ ]:
# Operations between arrays of different shapes

import numpy as np

# Broadcasting examples
a = np.array([1, 2, 3])
b = 2
print(a + b,"\n")  # Adds 2 to each element of 'a'

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([10, 20, 30])
print(c + d,"\n")  # Adds 'd' to each row of 'c'

e = np.array([[1, 2], [3, 4]])
f = np.array([10, 20])
print(e + f,"\n") # Adds f to each row of e

#More complex broadcasting
g = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
h = np.array([[9,10],[11,12]])
print(g + h)

[3 4 5] 

[[11 22 33]
 [14 25 36]] 

[[11 22]
 [13 24]] 

[[[10 12]
  [14 16]]

 [[14 16]
  [18 20]]]


In [ ]:
#Adding scalar to an array

import numpy as np

# Broadcasting examples
a = np.array([1, 2, 3])
b = 2
print(a + b)  # Adds 2 to each element of 'a'

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([10, 20, 30])
print(c + d)  # Adds 'd' to each row of 'c'

e = np.array([[1, 2], [3, 4]])
f = np.array([10, 20])
print(e + f) # Adds f to each row of e

#More complex broadcasting
g = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
h = np.array([[9,10],[11,12]])
g + h

[3 4 5]
[[11 22 33]
 [14 25 36]]
[[11 22]
 [13 24]]


array([[[10, 12],
        [14, 16]],

       [[14, 16],
        [18, 20]]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a + b)

[[11 22]
 [13 24]]


Indexing and Slicing

Accessing elements, rows, and columns

Boolean indexing

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[1, 2])  # Single element
print(arr[:, 1])  # All rows, second column
print(arr[arr > 5])  # Boolean indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[2 5 8]
[6 7 8 9]


Linear Algebra

Determinants, eigenvalues, solving equations

In [ ]:
a = np.array([[3, 1], [2, 4]])
print(a)
print("Determinant:", np.linalg.det(a))

[[3 1]
 [2 4]]
Determinant: 10.000000000000002


In [ ]:
import numpy as np
a=np.random.randint(2,100,9)
a=a.reshape(3,3)
print(a)
Determinant = np.linalg.det(a)
print("Determinant:", Determinant)

[[13 22 20]
 [67 67 21]
 [83 52 71]]
Determinant: -60202.99999999996


Exercise:

Add a column vector to a 2D matrix using broadcasting.

Extract a 2x2 submatrix from a 3x3 matrix.

Solve the system of equations

1. 2x + y = 5, x - 3y = -3
2. 2x + y - z = 1, x + 3y + 2z = 10, x - y + z = 0

In [35]:
a=np.random.randint(2,100,4)
a=a.reshape(2,2)
print(a)
b=([10,20])
print(b)
print(a+b)

[[46 60]
 [10 99]]
[10, 20]
[[ 56  80]
 [ 20 119]]


1. 2x2 Matrix

For a 2x2 matrix:


A = | a  b |
    | c  d |
Use code with caution
The determinant, denoted as det(A) or |A|, is calculated as:


det(A) = (a * d) - (b * c)
Use code with caution
Example:


A = | 2  3 |
    | 1  4 |

det(A) = (2 * 4) - (3 * 1) = 8 - 3 = 5
Use code with caution
2. 3x3 Matrix

For a 3x3 matrix:


A = | a  b  c |
    | d  e  f |
    | g  h  i |
Use code with caution
The determinant is calculated using the following formula:


det(A) = a(ei − fh) − b(di − fg) + c(dh − eg)
Use code with caution
This can be visualized as:

Expansion along the first row:
Take element a, multiply it by the determinant of the 2x2 submatrix formed by removing the row and column containing a (which is ei - fh).
Do the same for element b (multiply by di - fg) and element c (multiply by dh - eg).
Alternate the signs: +, -, +.
Example:


A = | 1  2  3 |
    | 4  5  6 |
    | 7  8  9 |

det(A) = 1(5*9 - 6*8) - 2(4*9 - 6*7) + 3(4*8 - 5*7)
       = 1(45 - 48) - 2(36 - 42) + 3(32 - 35)
       = -3 + 12 - 9
       = 0
Use code with caution
3. 4x4 Matrix and Beyond

For larger matrices like 4x4, the determinant calculation becomes more complex. The general approach involves:

Cofactor Expansion: Choose a row or column to expand along.
Calculate Cofactors: For each element in the chosen row/column, find its cofactor. The cofactor is the determinant of the submatrix formed by removing the row and column containing that element, multiplied by (-1)^(row + column).
Sum of Products: Multiply each element in the chosen row/column by its cofactor and sum the results.
Formula for a 4x4 matrix:


A = | a  b  c  d |
    | e  f  g  h |
    | i  j  k  l |
    | m  n  o  p |

det(A) = a * det(3x3 submatrix) - b * det(3x3 submatrix) + c * det(3x3 submatrix) - d * det(3x3 submatrix)
Use code with caution
Where each 3x3 submatrix is formed by removing the row and column containing the corresponding element (a, b, c, or d).

In practice, for matrices larger than 3x3, it's often more efficient to use numerical methods and software tools like NumPy to calculate determinants, as the manual calculations become quite tedious.

In [ ]:
# determine eigenvalues using numpy

import numpy as np

a = np.array([[3, 1], [2, 4]])
eigenvalues = np.linalg.eigvals(a)
print("Eigenvalues:", eigenvalues)


Eigenvalues: [2. 5.]


Eigenvalues and Eigenvectors

Eigenvalues (λ) and eigenvectors (v) are closely related concepts in linear algebra. They are defined for a square matrix (A).

Eigenvector (v): A non-zero vector that, when multiplied by the matrix (A), results in a scaled version of itself.
Eigenvalue (λ): The scaling factor by which the eigenvector is stretched or compressed when multiplied by the matrix (A).
The Eigenvalue Equation

The fundamental equation that governs eigenvalues and eigenvectors is:


A * v = λ * v
Use code with caution
where:

A is the square matrix.
v is the eigenvector.
λ is the eigenvalue.
Steps to Calculate Eigenvalues

Characteristic Equation: Rearrange the eigenvalue equation:

A * v - λ * v = 0
(A - λ * I) * v = 0
Use code with caution
where:

I is the identity matrix of the same size as A.
Determinant: For the above equation to have a non-zero solution for the eigenvector (v), the determinant of (A - λ * I) must be zero:

det(A - λ * I) = 0
Use code with caution
This equation is called the characteristic equation.

Solving for λ: The characteristic equation is a polynomial equation in λ. Solving this equation for λ gives you the eigenvalues of the matrix A.
Example: 2x2 Matrix

Let's consider a 2x2 matrix:


A = | a  b |
    | c  d |
Use code with caution
Characteristic Equation:

det(A - λ * I) = det(| a - λ  b |) = (a - λ)(d - λ) - (b * c) = 0
                       | c      d - λ |
Use code with caution
Solving for λ: Expand the determinant and solve the resulting quadratic equation for λ. The solutions are the eigenvalues.
Larger Matrices:

The process is similar for larger matrices, but the characteristic equation becomes a higher-degree polynomial, making it more complex to solve analytically. Numerical methods are often used to find eigenvalues in these cases.

In summary: Eigenvalues are found by solving the characteristic equation, which is obtained by setting the determinant of (A - λ * I) to zero. The solutions to this equation represent the

In [ ]:


import numpy as np

# Example matrix and column vector
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

# Add the column vector to the matrix using broadcasting
result = matrix + vector.reshape(3,1) # Reshape for proper column vector addition
result

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [38]:
import numpy as np

# Example 3x3 matrix
matrix = np.arange(1,65).reshape(4,4,4)

# Extract a 2x2 submatrix (e.g., top-left corner)
submatrix = matrix[1,1:3, : ]

print("Original Matrix:\n", matrix)
print("\n2x2 Submatrix:\n", submatrix)

Original Matrix:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]

2x2 Submatrix:
 [[21 22 23 24]
 [25 26 27 28]]


In [ ]:
# Solve 2 variable system of equations using Numpy

import numpy as np

# Example system of equations:
# 2x + y = 5
# x - 3y = -3

# Represent the coefficients as a matrix
A = np.array([[2, 1], [1, -3]])

# Represent the constants as a vector
b = np.array([5, -3])

# Solve the system of equations using numpy.linalg.solve
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:")
print("x =", x[0])
print("y =", x[1])

Solution:
x = 1.7142857142857144
y = 1.5714285714285714


In [ ]:
# Solve 3 variable system of equations using Numpy

import numpy as np

# Example system of equations:
# 2x + y - z = 1
# x + 3y + 2z = 10
# x - y + z = 0

# Represent the coefficients as a matrix
A = np.array([[2, 1, -1],
              [1, 3, 2],
              [1, -1, 1]])

# Represent the constants as a vector
b = np.array([1, 10, 0])

# Solve the system of equations using numpy.linalg.solve
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:")
print("x =", x[0])
print("y =", x[1])
print("z =", x[2])

Solution:
x = 0.3333333333333335
y = 2.0666666666666664
z = 1.7333333333333336


np.linalg.solve: This is a function from NumPy's linear algebra module (linalg). Its purpose is to solve a system of linear equations.

A: This variable represents the coefficient matrix of your system of equations. It's a NumPy array containing the coefficients of the unknowns (like 'x' and 'y' in a typical system).

b: This variable represents the constant vector in your system of equations. It's a NumPy array containing the values on the right-hand side of the equation.

x: This is where the result is stored. The np.linalg.solve function calculates the values of the unknowns that satisfy the equations and assigns them to x. x will also be a NumPy array.

**Matrix Operations: Dot Product**

1. Create two 2x2 matrices A and B. Compute their dot product using np.dot().

2. Verify the result by manually calculating the dot product of the matrices.
3. Create a 3x3 matrix C and a 3x1 matrix D. Find their dot product.
4. Generate two random 4x4 matrices using np.random.rand and calculate their dot product.
5. Check if the dot product of two matrices is commutative (A @ B == B @ A).


In [ ]:
import numpy as np

# 1. Compute the dot product of two 2x2 matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print("Dot Product of A and B:\n", dot_product)

# 2. Verify manually
manual_result = [[19, 22], [43, 50]]  # Example calculation
print("Manual Dot Product Verification:\n", manual_result)

# 3. Dot product of a 3x3 matrix and a 3x1 matrix
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1], [2], [3]])
dot_product_CD = np.dot(C, D)
print("Dot Product of C and D:\n", dot_product_CD)

# 4. Random 4x4 matrices
M1 = np.random.rand(4, 4)
M2 = np.random.rand(4, 4)
print("Dot Product of Random Matrices:\n", np.dot(M1, M2))

# 5. Commutative check
print("A @ B == B @ A:", np.array_equal(np.dot(A, B), np.dot(B, A)))


Dot Product of A and B:
 [[19 22]
 [43 50]]
Manual Dot Product Verification:
 [[19, 22], [43, 50]]
Dot Product of C and D:
 [[14]
 [32]
 [50]]
Dot Product of Random Matrices:
 [[0.68967233 0.28795165 1.0181268  0.81833266]
 [0.73676179 0.43932955 1.28220277 0.98061345]
 [0.73571692 0.27076603 1.18920706 0.86477279]
 [0.534695   0.36308627 0.73467828 0.87830395]]
A @ B == B @ A: False


**Matrix Operations: Multiplication**


1. Create two matrices, M1 and M2, and perform element-wise multiplication using *.
2. Generate two matrices of different sizes that allow broadcasting and multiply them.
3. Create a 3x3 identity matrix and multiply it with another 3x3 matrix. Verify the result.
4. Multiply a matrix by a scalar value and observe the change in values.
5. Create a 2D matrix and a 1D array. Multiply them using broadcasting rules.

In [ ]:
# 1. Element-wise multiplication
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])
print("Element-wise Multiplication:\n", M1 * M2)

# 2. Broadcasting multiplication
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
print("Broadcasting Multiplication:\n", matrix * vector)

# 3. Identity matrix multiplication
identity_matrix = np.eye(3)
other_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Identity Matrix Multiplication:\n", np.dot(identity_matrix, other_matrix))

# 4. Scalar multiplication
scalar_matrix = M1 * 3
print("Scalar Multiplication:\n", scalar_matrix)

# 5. Broadcasting with 2D and 1D
array_1d = np.array([1, 2])
matrix_2d = np.array([[1, 2], [3, 4]])
print("2D and 1D Multiplication:\n", matrix_2d * array_1d)


Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Broadcasting Multiplication:
 [[ 1  4  9]
 [ 4 10 18]]
Identity Matrix Multiplication:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Scalar Multiplication:
 [[ 3  6]
 [ 9 12]]
2D and 1D Multiplication:
 [[1 4]
 [3 8]]


**Matrix Operations: Transpose**

Create a 2x3 matrix and find its transpose using np.transpose() and .T.

Verify that the transpose of a transpose returns the original matrix.

Create a random 4x4 matrix and calculate its transpose. Verify symmetry for symmetric matrices.

Multiply a 2x2 matrix by its transpose. Check if the result is symmetric.

Find the transpose of a 3D array (shape 2x3x4) along specified axes.


In [ ]:
# 1. Transpose of 2x3 matrix
import random
matrix_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nSimple matrix\n",matrix_2x3)
print("\nTranspose:\n", matrix_2x3.T)

# 2. Transpose of a transpose
print("Transpose of Transpose:\n", (matrix_2x3.T).T)

# 3. Random 4x4 matrix transpose
random_matrix = np.random.randint(1,100,(4, 4) )
#random_matrix = np.reshape(4, 4)
print("\nRandom Matrix is:\n",random_matrix)
print("Random Matrix Transpose:\n", random_matrix.T)

# 4. Symmetric matrix test
symmetric_matrix = np.array([[1, 2], [2, 1]])
print("\n Matrix is \n",symmetric_matrix,"\nand transpose is\n",symmetric_matrix.T)
print("Symmetric Matrix Test (A == A.T):", np.array_equal(symmetric_matrix, symmetric_matrix.T))

# 5. Transpose along specified axes
tensor = np.random.rand(2, 3, 4)
print("\nTensor\n",tensor)
#print("Transposed Tensor:\n", np.transpose(tensor, (1, 2, 0)))
transposed = np.transpose(tensor, (1, 0, 2))
print("Transposed Tensor:\n", transposed)
print("Transposed Tensor Shape:", transposed.shape)



Simple matrix
 [[1 2 3]
 [4 5 6]]

Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Transpose of Transpose:
 [[1 2 3]
 [4 5 6]]

Random Matrix is:
 [[80 37 86 27]
 [11 24 54 16]
 [75 38 39 38]
 [12 72 25 20]]
Random Matrix Transpose:
 [[80 11 75 12]
 [37 24 38 72]
 [86 54 39 25]
 [27 16 38 20]]

 Matrix is 
 [[1 2]
 [2 1]] 
and transpose is
 [[1 2]
 [2 1]]
Symmetric Matrix Test (A == A.T): True

Tensor
 [[[0.79929986 0.80233577 0.77379507 0.33095516]
  [0.47049066 0.2434217  0.82585226 0.74201259]
  [0.0392203  0.44120555 0.05355808 0.92710337]]

 [[0.93929522 0.71809071 0.43303289 0.66349404]
  [0.01508682 0.4945011  0.27469244 0.95902088]
  [0.99140835 0.01172529 0.17198523 0.87748845]]]
Transposed Tensor:
 [[[0.79929986 0.80233577 0.77379507 0.33095516]
  [0.93929522 0.71809071 0.43303289 0.66349404]]

 [[0.47049066 0.2434217  0.82585226 0.74201259]
  [0.01508682 0.4945011  0.27469244 0.95902088]]

 [[0.0392203  0.44120555 0.05355808 0.92710337]
  [0.99140835 0.01172529 0.17198523 0.87748845]]]
T

Broadcasting


Add a scalar (e.g., 5) to a 1D array of size 5.

Create a 2x3 matrix and a 1D array of size 3. Add them using broadcasting.

Multiply a 2x3 matrix with a 1D array of size 2 along the correct axis.

Create a 3x3x3 tensor and add a scalar to all its elements.

Divide a 4x4 matrix by a 1D array of size 4, broadcasting along columns.


In [ ]:
# 1. Adding scalar to 1D array
array = np.array([1, 2, 3, 4, 5])
print("Array + Scalar:\n", array + 5)

# 2. Adding 2x3 matrix and 1D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
print("Matrix + Vector:\n", matrix + vector)

# 3. Multiply with broadcasting
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2])
print("Matrix * Vector (Broadcasting):\n", (matrix.T * vector).T)

# 4. Add scalar to tensor
tensor = np.random.rand(3, 3, 3)
print("Tensor + Scalar:\n", tensor + 1)

# 5. Divide with broadcasting
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([10, 20, 30])
print("Matrix / Vector:\n", matrix / vector)


Array + Scalar:
 [ 6  7  8  9 10]
Matrix + Vector:
 [[2 4 6]
 [5 7 9]]
Matrix * Vector (Broadcasting):
 [[ 1  2  3]
 [ 8 10 12]]
Tensor + Scalar:
 [[[1.99795175 1.15950288 1.70388842]
  [1.6010123  1.53394955 1.32450629]
  [1.13042041 1.65476485 1.39103421]]

 [[1.4077305  1.09511549 1.75056348]
  [1.40312784 1.7057094  1.07355469]
  [1.04549537 1.83341435 1.54873766]]

 [[1.33667265 1.98730388 1.27864577]
  [1.65112015 1.20889437 1.33860335]
  [1.96216331 1.85625443 1.55135205]]]
Matrix / Vector:
 [[1.  1.  1. ]
 [4.  2.5 2. ]]


5. Indexing

Create a 4x4 matrix and access the element at the second row, third column.

Create a 3x3 matrix and access all elements in the second row.

Create a 3x3x3 tensor and access the first layer (2D slice).

Modify the element at position (2, 2) in a 4x4 matrix to 10.

Access the last element of each row in a 3x4 matrix.


In [ ]:
# 1. Access specific element
matrix = np.array([[1, 2], [3, 4]])
print("Element at (1,1):", matrix[1, 1])

# 2. Access row
print("Second row:", matrix[1])

# 3. Access layer in 3D tensor
tensor = np.random.rand(3, 3, 3)
print("First Layer:\n", tensor[0])

# 4. Modify specific element
matrix[1, 1] = 10
print("Modified Matrix:\n", matrix)

# 5. Last element of each row
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Last Elements of Rows:", matrix[:, -1])


Element at (1,1): 4
Second row: [3 4]
First Layer:
 [[0.26703911 0.2279654  0.95134216]
 [0.44645328 0.43974664 0.28539294]
 [0.49550537 0.52646878 0.93153978]]
Modified Matrix:
 [[ 1  2]
 [ 3 10]]
Last Elements of Rows: [3 6]


6. Slicing

Create a 1D array of 10 elements and slice out the first 5 elements.

Create a 4x4 matrix and extract the first two rows and columns.

Create a 3D tensor (shape 3x4x5) and slice out the first two layers.

Extract every alternate row from a 5x5 matrix.

Slice a 1D array to reverse its elements.

In [ ]:
# 1. Slice 1D array
array = np.arange(10)
print("First 5 Elements:", array[:5])

# 2. Slice 4x4 matrix
matrix = np.arange(16).reshape(4, 4)
print("Top-Left 2x2:\n", matrix[:2, :2])

# 3. Slice 3D tensor
tensor = np.random.rand(3, 4, 5)
print("First Two Layers:\n", tensor[:2])

# 4. Alternate rows
print("Alternate Rows:\n", matrix[::2])

# 5. Reverse array
print("Reversed Array:", array[::-1])


First 5 Elements: [0 1 2 3 4]
Top-Left 2x2:
 [[0 1]
 [4 5]]
First Two Layers:
 [[[0.42736739 0.74606331 0.42883753 0.70568205 0.93155207]
  [0.322549   0.04541889 0.7165597  0.60373562 0.20847626]
  [0.13856056 0.31625453 0.96717288 0.97352703 0.24004969]
  [0.47755891 0.76345357 0.535128   0.46510682 0.48918243]]

 [[0.44143343 0.14744112 0.6557017  0.04264702 0.46631896]
  [0.87393026 0.24361056 0.91283496 0.93071878 0.98020823]
  [0.73265471 0.63793213 0.85696044 0.96760108 0.26444397]
  [0.53890511 0.28899857 0.04741582 0.84415652 0.43018971]]]
Alternate Rows:
 [[ 0  1  2  3]
 [ 8  9 10 11]]
Reversed Array: [9 8 7 6 5 4 3 2 1 0]


7. Boolean Indexing

Create a 1D array of integers and filter out all even numbers.

Create a 5x5 matrix and replace all values greater than 10 with 0.

Generate a random array of 20 elements and select all values greater than the
mean.

Create a 1D array and find the indices where the values are divisible by 3.

Replace negative values in a matrix with their absolute values using boolean indexing.

In [ ]:
# 1. Filter even numbers
array = np.arange(10)
print("Even Numbers:", array[array % 2 == 0])

# 2. Replace > 10 with 0
matrix = np.random.randint(0, 20, (4, 4))
matrix[matrix > 10] = 0
print("Replaced Matrix:\n", matrix)

# 3. Values greater than mean
random_array = np.random.rand(20)
print("Greater than Mean:", random_array[random_array > random_array.mean()])

# 4. Divisible by 3
print("Indices Divisible by 3:", np.where(array % 3 == 0))

# 5. Replace negatives with absolute
matrix = np.array([[1, -2], [-3, 4]])
matrix[matrix < 0] = np.abs(matrix[matrix < 0])
print("Positive Matrix:\n", matrix)


Even Numbers: [0 2 4 6 8]
Replaced Matrix:
 [[ 6  0  3  0]
 [ 0  0  3  0]
 [ 3  0  5  0]
 [ 0  0  6 10]]
Greater than Mean: [0.84299829 0.59850893 0.93243468 0.73716368 0.76036955 0.99426542
 0.94461153 0.79232537 0.72323916 0.87597436]
Indices Divisible by 3: (array([0, 3, 6, 9]),)
Positive Matrix:
 [[1 2]
 [3 4]]


8. Linear Algebra: Determinants

Create a 2x2 matrix and compute its determinant using np.linalg.det.

Verify that the determinant of a singular matrix is 0.

Calculate the determinant of a 3x3 random matrix.

Check if the determinant of a matrix product equals the product of determinants.

Create a 4x4 identity matrix and calculate its determinant.


In [ ]:
import numpy as np

# 1. Determinant of a 2x2 matrix
matrix_2x2 = np.array([[4, 6], [3, 8]])
det_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of 2x2 Matrix:", det_2x2)

# 2. Determinant of a singular matrix
singular_matrix = np.array([[1, 2], [2, 4]])
det_singular = np.linalg.det(singular_matrix)
print("Determinant of Singular Matrix:", det_singular)

# 3. Determinant of a 3x3 matrix
matrix_3x3 = np.random.rand(3, 3)
det_3x3 = np.linalg.det(matrix_3x3)
print("Determinant of 3x3 Matrix:", det_3x3)

# 4. Check determinant property for matrix product
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
product_matrix = np.dot(A, B)
det_product = np.linalg.det(product_matrix)
det_check = np.linalg.det(A) * np.linalg.det(B)
print("Det of Product == Product of Dets:", np.isclose(det_product, det_check))

# 5. Determinant of identity matrix
identity_matrix = np.eye(4)
det_identity = np.linalg.det(identity_matrix)
print("Determinant of Identity Matrix:", det_identity)


Determinant of 2x2 Matrix: 14.000000000000004
Determinant of Singular Matrix: 0.0
Determinant of 3x3 Matrix: -0.2801725496543638
Det of Product == Product of Dets: True
Determinant of Identity Matrix: 1.0


**Linear Algebra: Eigenvalues**

Create a 2x2 symmetric matrix and calculate its eigenvalues using np.linalg.eig.

Verify the eigenvalue equation
𝐴
𝑥
=
𝜆
𝑥
Ax=λx for a matrix and its eigenvectors.

Calculate the eigenvalues of a 3x3 diagonal matrix.

Generate a 4x4 random matrix and compute its eigenvalues.

Check if the sum of eigenvalues equals the trace of the matrix.

In [ ]:
# 1. Eigenvalues of a symmetric matrix
symmetric_matrix = np.array([[2, -1], [-1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(symmetric_matrix)
print("Eigenvalues of Symmetric Matrix:", eigenvalues)

# 2. Verify eigenvalue equation
A = np.array([[4, 1], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
v = eigenvectors[:, 0]  # First eigenvector
lambda_ = eigenvalues[0]  # First eigenvalue
print("Ax:", np.dot(A, v))
print("λx:", lambda_ * v)

# 3. Eigenvalues of a diagonal matrix
diagonal_matrix = np.diag([10, 20, 30])
eigenvalues_diag = np.linalg.eigvals(diagonal_matrix)
print("Eigenvalues of Diagonal Matrix:", eigenvalues_diag)

# 4. Random 4x4 matrix
random_matrix = np.random.rand(4, 4)
eigenvalues_random = np.linalg.eigvals(random_matrix)
print("Eigenvalues of Random Matrix:", eigenvalues_random)

# 5. Sum of eigenvalues == trace
matrix = np.array([[2, 0], [0, 3]])
eigenvalues = np.linalg.eigvals(matrix)
print("Sum of Eigenvalues:", np.sum(eigenvalues))
print("Trace of Matrix:", np.trace(matrix))


Eigenvalues of Symmetric Matrix: [3. 1.]
Ax: [3.53553391 3.53553391]
λx: [3.53553391 3.53553391]
Eigenvalues of Diagonal Matrix: [10. 20. 30.]
Eigenvalues of Random Matrix: [ 1.89292053+0.j          0.16871246+0.35144213j  0.16871246-0.35144213j
 -0.25995674+0.j        ]
Sum of Eigenvalues: 5.0
Trace of Matrix: 5


**Linear Algebra: Solving Equations**

Solve the system of equations

2
𝑥
+
3
𝑦
=
8
and
𝑥
−
𝑦
=
2
using np.linalg.solve.

Create a 3x3 matrix
𝐴
and a vector
𝐵
Solve
𝐴
𝑥
=
𝐵


Verify that the solution
𝑥
satisfies
𝐴
𝑥
=
𝐵


Solve a system of linear equations where the coefficient matrix is singular. Handle the error.

Generate a random matrix
𝐴
and vector
𝐵
Solve
𝐴
𝑥
=
𝐵
for
𝑥
.


In [ ]:
# 1. Solve 2x2 system of equations
coeff_matrix = np.array([[2, 3], [1, -1]])
constants = np.array([8, 2])
solution = np.linalg.solve(coeff_matrix, constants)
print("Solution to Equations:", solution)

# 2. Solve a 3x3 system
A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])
B = np.array([8, -11, -3])
solution_3x3 = np.linalg.solve(A, B)
print("Solution to 3x3 System:", solution_3x3)

# 3. Verify solution satisfies Ax = B
check = np.allclose(np.dot(A, solution_3x3), B)
print("Does Ax = B?", check)

# 4. Singular matrix error
try:
    singular_matrix = np.array([[1, 2], [2, 4]])
    np.linalg.solve(singular_matrix, np.array([1, 2]))
except np.linalg.LinAlgError as e:
    print("Error with Singular Matrix:", e)

# 5. Solve random system
random_coeff = np.random.rand(4, 4)
random_constants = np.random.rand(4)
random_solution = np.linalg.solve(random_coeff, random_constants)
print("Solution to Random System:", random_solution)


Solution to Equations: [2.8 0.8]
Solution to 3x3 System: [ 2.  3. -1.]
Does Ax = B? True
Error with Singular Matrix: Singular matrix
Solution to Random System: [ 0.74827609  0.05479382 -0.04356064 -0.194848  ]


In [ ]:
import numpy as np

# Create a 3x3 grayscale image with random pixel intensities (0-255)
grayscale_image = np.random.randint(0, 256, (3, 3))
print("Original Grayscale Image:\n", grayscale_image)

# Double the intensity and clip the values to stay within 0-255
transformed_image = np.clip(grayscale_image * 2, 0, 255)
print("\nTransformed Grayscale Image (Doubled Intensity):\n", transformed_image)


Original Grayscale Image:
 [[ 55  91 214]
 [196 103  14]
 [118 176 188]]

Transformed Grayscale Image (Doubled Intensity):
 [[110 182 255]
 [255 206  28]
 [236 255 255]]


In [ ]:
coin_tosses = np.random.choice([0, 1], size=100)

# Calculate the number of heads
num_heads = np.sum(coin_tosses)

# Calculate the probability of heads
probability_heads = num_heads / 100
print("\nNumber of Heads:", num_heads)
print("Probability of Getting Heads:", probability_heads)


Number of Heads: 49
Probability of Getting Heads: 0.49
